# Project Information
site_name: BsidesSF Volunteer Runbook

# Repository Information
repo_url: https://github.com/BSidesSF/volunteer-runbook
edit_uri: edit/main/docs/

# Theme settings
theme:
  name: readthedocs
  logo: images/bsidessf-logo.png

# Making RTD work for larger screens
extra_css: [extra.css]

# Plugins
plugins:
  - search
  - mermaid2

# Navigation 
nav:
  - Home: 
    - index.md
  - Safety Ops: 
    - safety-ops/for-all-safety-ops.md
    - safety-ops/incidents.md
    - safety-ops/positions.md
  - Behind The Scenes Roles:
    - behind-the-scenes/bag-stuffing.md
    - behind-the-scenes/runner.md
    - behind-the-scenes/setup-and-teardown.md
  - Attendee Facing Roles:
    - attendee-facing/coat-check.md
    - attendee-facing/information-desk.md
    - attendee-facing/party.md
    - attendee-facing/registration.md
    - attendee-facing/room-moderator.md
    - attendee-facing/social-media.md