name: mkdocs-deploy-to-gh-pages
run-name: Deploying static site files to https://bsidessf.org/volunteer-runbook/ by @${{ github.actor }}

on:
  push:
    branches:
      - main
      
permissions: write-all

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull the Deployed Branch Down for Chantes
        run:  git pull origin deployed
      - name: Install Dependencies
        run: pwd && ls && pip install -r requirements.txt
      - name: Build and Deploy Site
        run: mkdocs gh-deploy --clean --remote-branch deployed --theme readthedocs
